exclude:
  - "**/*.patch"
  - "**/node_modules/**/*"
  - "**/vendor/**/*"
  - ".github/workflows/**/*"
  - "dist/**/*" # TODO: add to Restyled-proper
restylers:
  - clang-format:
      enabled: false
  - prettier:
      image: restyled/restyler-prettier:v1.19.1-2
  - "*"
