name: "Stack cache"
author: "freckle"
description: "Caching Action for Stack-based Haskell projects"
runs:
  using: "node16"
  main: "dist/restore/index.js"
  post: "dist/save/index.js"
inputs:
  stack-yaml:
    description: "Path to stack.yaml"
    required: true
    default: "stack.yaml"
  working-directory:
    description: "Directory within which to run and save"
    required: true
    default: "."
  prefix:
    description: "A prefix to include on keys; useful for cache busting or versioning"
    required: false
    default: ""
outputs:
  cache-hit:
    description: "A boolean value to indicate an exact match was found for the primary key"
