name: "Stack cache"
author: "freckle"
description: "Caching Action for Stack-based Haskell projects"
inputs:
  stack-yaml:
    description: "Path to stack.yaml"
    required: true
    default: "stack.yaml"
  working-directory:
    description: "Directory within which to run and save"
    required: true
    default: "."
  prefix:
    description: "A prefix to include on keys; useful for cache busting or versioning"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: freckle/stack-action@v5
      env:
        STACK_YAML: ${{ inputs.stack-yaml }}
      with:
        working-directory: ${{ inputs.working-directory }}
        cache-prefix: ${{ inputs.cache-prefix }}

        # Avoid other stack-action behavior, as much as we can
        stack-build-arguments: --dry-run
        install-stack: false
        upgrade-stack: false
