name: Build

on:
  push:
    branches:
      - master

env:
  node_version: "12.x"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install JS dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Commit and push distified version to master
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: 'Update distified version'
          file_pattern: 'dist/**/*.js'
