name: Mergeabot

on:
  schedule:
    - cron: "0 0 * * *"

  # test changes to this file itself
  pull_request:
    paths:
      - .github/workflows/mergeabot.yml

jobs:
  mergeabot:
    runs-on: ubuntu-latest
    steps:
      - uses: freckle/mergeabot-action@v1
        with:
          quarantine-days: 1
